#!/usr/bin/env pymol

# PyMOL rendering script for AutoAntibiotic PBP2a binding modes
# Generated by generate_publication_figures.py
# Load and render: pymol -qx figure5_pymol_script.pml

# Load receptor (PBP2a holo, PDB 3ZG0)
fetch 3ZG0, pbp2a
remove solvent
hide everything
show cartoon
color lightblue, pbp2a

# Highlight catalytic triad
select catalytic_triad, resi 403+406+446
show sticks, catalytic_triad
color red, catalytic_triad
label catalytic_triad, ""

# Load docked poses

# Load ALL_QU05
# To load the docked pose, convert SMILES to 3D and align:
#   from rdkit import Chem
#   from rdkit.Chem import AllChem
#   mol = Chem.MolFromSmiles('O=c1[nH]c2ccc3cccnc3c2n1Cc1ccc(-c2ccccc2)cc1')
#   mol = Chem.AddHs(mol)
#   AllChem.EmbedMolecule(mol)
#   Chem.MolToPDBFile(mol, 'ALL_QU05_pose.pdb')
cd output/pdb/
load ALL_QU05_pose.pdb, ALL_QU05
show sticks, ALL_QU05
color marine, ALL_QU05

# Load BRICS_01163
# To load the docked pose, convert SMILES to 3D and align:
#   from rdkit import Chem
#   from rdkit.Chem import AllChem
#   mol = Chem.MolFromSmiles('O=c1[nH]c(=O)n(Cc2ccc(-n3c(=O)[nH]c4ccccc43)cc2)c2ccccc12')
#   mol = Chem.AddHs(mol)
#   AllChem.EmbedMolecule(mol)
#   Chem.MolToPDBFile(mol, 'BRICS_01163_pose.pdb')
cd output/pdb/
load BRICS_01163_pose.pdb, BRICS_01163
show sticks, BRICS_01163
color marine, BRICS_01163

# Load BRICS_0022
# To load the docked pose, convert SMILES to 3D and align:
#   from rdkit import Chem
#   from rdkit.Chem import AllChem
#   mol = Chem.MolFromSmiles('COc1ccc(C=Cc2cn(Cc3ccnc(C4CCNC4=O)n3)c(=O)[nH]c2=O)cc1O')
#   mol = Chem.AddHs(mol)
#   AllChem.EmbedMolecule(mol)
#   Chem.MolToPDBFile(mol, 'BRICS_0022_pose.pdb')
cd output/pdb/
load BRICS_0022_pose.pdb, BRICS_0022
show sticks, BRICS_0022
color marine, BRICS_0022

# Render settings
set ray_trace_frames, 1
set antialias, 2
set depth_cue, 0
bg_color white
# Ray trace: ray 2400, 2400

# Generate 2D interaction diagram manually or with LigPlot+
# Figure 5 shows 3D binding mode with:
#   - PBP2a surface (transparent)
#   - Catalytic residues (red sticks, labelled)
#   - Lead compound (marine sticks)
#   - H-bonds as yellow dashed lines
