#!/usr/bin/env python3
"""
Enrichment validation for the AutoAntibiotic PBP2a screen.

Labels come ONLY from data/known_actives.csv (experimental PBP2a binders)
and data/known_decoys.csv (property-matched non-binders, generated by
BRICS recombination independently of any docking score).

Computes ROC-AUC, EF_1% and EF_5% against the true labels.

Usage:
    AUTOANTIBIOTIC_MODE=science python scripts/enrichment_validation.py

Outputs:
    output/enrichment_results.json
    output/enrichment_roc.png
"""
from __future__ import annotations

import os
import sys
import json
import csv
import logging

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from rdkit import Chem

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import discovery_pipeline as P
from config.constants import (
    ACTIVE_BOX_SIZE, ACTIVE_SITE_RESIDUES,
)

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger("enrichment")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "output")
DATA = os.path.join(REPO, "data")
os.makedirs(OUT, exist_ok=True)


def load_benchmark(data_dir: str):
    """Load known actives and decoys from CSVs. Returns (records, labels).

    Labels are 1 for known actives, 0 for decoys -- determined SOLELY
    from experimental measurement / independent property matching, never
    from a docking energy threshold.
    """
    records = []
    labels = []

    # Known actives (experimental binders)
    actives_path = os.path.join(data_dir, "known_actives.csv")
    if not os.path.exists(actives_path):
        log.error(f"  Known-actives file not found: {actives_path}")
        sys.exit(1)
    with open(actives_path, newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            smi = row["smiles"].strip()
            cid = row["compound_id"].strip()
            if smi:
                records.append(P.CompoundRecord(compound_id=cid, smiles=smi))
                labels.append(1)  # active = known experimental binder
    log.info(f"  Loaded {sum(labels)} known actives")

    # Known decoys (property-matched non-binders)
    decoys_path = os.path.join(data_dir, "known_decoys.csv")
    if not os.path.exists(decoys_path):
        log.error(f"  Known-decoys file not found: {decoys_path}")
        sys.exit(1)
    with open(decoys_path, newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            smi = row["smiles"].strip()
            cid = row["compound_id"].strip()
            if smi:
                records.append(P.CompoundRecord(compound_id=cid, smiles=smi))
                labels.append(0)  # decoy = property-matched non-binder
    log.info(f"  Loaded {labels.count(0)} known decoys")

    return records, labels


def compute_roc(labels, scores):
    """Return (fpr_list, tpr_list, auc) for binary labels and higher=better scores."""
    order = np.argsort(-np.asarray(scores, dtype=float))
    labels = np.asarray(labels, dtype=int)[order]
    n_pos = int(labels.sum())
    n_neg = len(labels) - n_pos
    if n_pos == 0 or n_neg == 0:
        return [0.0, 1.0], [0.0, 1.0], 0.5
    tpr = [0.0]
    fpr = [0.0]
    tp = fp = 0
    prev_fpr = prev_tpr = 0.0
    auc = 0.0
    for lab in labels:
        if lab == 1:
            tp += 1
        else:
            fp += 1
        cur_tpr = tp / n_pos
        cur_fpr = fp / n_neg
        auc += (cur_fpr - prev_fpr) * (cur_tpr + prev_tpr) / 2.0
        tpr.append(cur_tpr)
        fpr.append(cur_fpr)
        prev_fpr, prev_tpr = cur_fpr, cur_tpr
    auc += (1.0 - prev_fpr) * (1.0 + prev_tpr) / 2.0
    return fpr, tpr, auc


def main():
    config = P.load_config()
    config["mode"] = "science"
    deps = P.check_dependencies()
    if not deps["USE_VINA"]:
        log.error("Vina required for enrichment validation. Aborting.")
        sys.exit(1)

    pdb_dir = os.path.join(OUT, "pdb_enrich")
    work_dir = os.path.join(OUT, "workdir_enrich")
    os.makedirs(pdb_dir, exist_ok=True)
    os.makedirs(work_dir, exist_ok=True)

    # Target prep
    _orig_clean = P.clean_pdb_structure
    def _cached_clean(pdb_path, out_path, **kw):
        pdbqt = out_path.replace(".pdb", ".pdbqt")
        if (os.path.exists(out_path) and os.path.getsize(out_path) > 0
                and os.path.exists(pdbqt) and os.path.getsize(pdbqt) > 0):
            return pdbqt
        return _orig_clean(pdb_path, out_path, **kw)

    P.clean_pdb_structure = _cached_clean
    targets = P.prepare_targets(pdb_dir, work_dir, deps, config=config)
    pb2pa = targets["PBP2a"]
    receptor_pdbqts = pb2pa["receptor_pdbqts"]
    active_center = pb2pa["active_center"]
    cleaned_pdb = pb2pa["cleaned_pdb"]
    active_box = P._auto_box_size(
        cleaned_pdb, active_center, ACTIVE_BOX_SIZE,
        min_size=15.0, max_size=20.0, site_residues=ACTIVE_SITE_RESIDUES,
    )
    log.info(f"  Active-site box: {active_box}; center: {active_center}")

    # Load benchmark
    records, labels = load_benchmark(DATA)

    # Consensus docking against PBP2a active site
    log.info(f"  Docking {len(records)} compounds against PBP2a active site...")
    docked = P._consensus_dock(
        records, receptor_pdbqts, active_center, active_box,
        work_dir, "active", use_vina=True,
    )
    energies = {rec.compound_id: e for rec, e in docked}

    # ROC / EF with true labels (NO fallback labeling from docking energy)
    ids = [r.compound_id for r in records]
    scores = [- (energies[cid] if energies[cid] is not None else 1e9) for cid in ids]
    fpr, tpr, auc = compute_roc(labels, scores)

    N = len(ids)
    n_act = sum(labels)
    k1 = max(1, round(0.01 * N))
    k5 = max(1, round(0.05 * N))
    ranked = sorted(ids, key=lambda c: (energies[c] if energies[c] is not None else 1e9))
    act_in_1 = sum(1 for c in ranked[:k1] if labels[ids.index(c)] == 1)
    act_in_5 = sum(1 for c in ranked[:k5] if labels[ids.index(c)] == 1)
    ef1 = (act_in_1 / n_act) / (k1 / N) if n_act else 0.0
    ef5 = (act_in_5 / n_act) / (k5 / N) if n_act else 0.0

    passed = (auc >= 0.7) and (ef1 >= 5.0)
    result = {
        "n_compounds": N,
        "n_actives": n_act,
        "n_decoys": N - n_act,
        "auc": round(float(auc), 4),
        "ef_1pct": round(float(ef1), 3),
        "ef_5pct": round(float(ef5), 3),
        "active_box": list(active_box),
        "verdict": "PASS" if passed else "FAIL",
        "label_source": "independent (known_actives.csv / known_decoys.csv)",
    }
    with open(os.path.join(OUT, "enrichment_results.json"), "w") as fh:
        json.dump(result, fh, indent=2)

    # ROC plot
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.plot(fpr, tpr, "b-", lw=2, label=f"ROC (AUC={auc:.3f})")
    ax.plot([0, 1], [0, 1], "k--", lw=1)
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.set_title("PBP2a Enrichment ROC (independent labels)")
    ax.legend(loc="lower right")
    fig.tight_layout()
    fig.savefig(os.path.join(OUT, "enrichment_roc.png"), dpi=300)
    plt.close(fig)

    # EF bar chart
    fig2, ax2 = plt.subplots(figsize=(4, 3))
    ax2.bar(["EF_1%", "EF_5%"], [ef1, ef5], color=["#2c7fb8", "#7fcdbb"])
    ax2.axhline(5, color="r", ls="--", lw=1, label="pass threshold (5)")
    ax2.set_ylabel("Enrichment Factor")
    ax2.set_title("Enrichment Factors (independent labels)")
    ax2.legend()
    fig2.tight_layout()
    fig2.savefig(os.path.join(OUT, "enrichment_ef.png"), dpi=300)
    plt.close(fig2)

    log.info("=" * 50)
    log.info(f"  Enrichment validation (independent labels): AUC={auc:.3f}  "
             f"EF_1%={ef1:.2f}  EF_5%={ef5:.2f}")
    log.info(f"  VERDICT: {'PASS' if passed else 'FAIL'} "
             f"(AUC>=0.7 and EF_1%>=5 required)")
    log.info("=" * 50)
    sys.exit(0 if passed else 2)


if __name__ == "__main__":
    main()
